### ISSUE TITLE
Display error when passing wrong structured arrays

### ISSUE THREAD

**Issue by adius** [adius/shaven#8]
Instead of

```
TypeError: Cannot read property 'forEach' of undefined
    at shaven (/Users/adrian/Projects/fakesome/node_modules/shaven/src/index.js:140:20)
    at shaven (/Users/adrian/Projects/fakesome/node_modules/shaven/src/index.js:97:4)
    at shaven (/Users/adrian/Projects/fakesome/node_modules/shaven/src/index.js:97:4)
    at shaven (/Users/adrian/Projects/fakesome/node_modules/shaven/src/index.js:97:4)
```

**Comment by adius** [comment]
Probably obsolete
